package: yform_autocomplete
version: "0.0.1-dev"
name: YForm Autocomplete
author: eaCe
supportpage: https://github.com/eaCe/yform_autocomplete

requires:
    redaxo: ^5.12.0
    php:
        version: '>=7.4'

page:
    title: YForm Autocomplete
    perm: admin
    icon: rex-icon fa-list-alt
    subpages:
        settings: { title: translate:settings }
        help: { title: translate:help, subPath: README.md, icon: rex-icon fa-question-circle, itemclass: pull-right }

load: early
